####################################
# Configurações de Desenvolvimento
####################################

####################################
# Configurações do Banco de Dados
####################################
spring.datasource.url=jdbc:postgresql://localhost:5432/desculpaai_dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

####################################
# Configurações de Logging
####################################
logging.level.root=INFO
logging.level.com.hackathon.DesculpaAI=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

####################################
# Swagger/OpenAPI
####################################
springdoc.swagger-ui.enabled=true

####################################
# Devtools
####################################
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
